import { ROLES } from './roles';
import { ROUTES } from './routes';

export const ROLE_LABELS = {
  [ROLES.VICTIM]: 'Victim',
  [ROLES.HELPER]: 'Helper',
  [ROLES.AUTHORITY]: 'Authority',
  [ROLES.ADMIN]: 'Admin',
};

export const ROLE_GROUPS = {
  EVERYONE: [ROLES.VICTIM, ROLES.HELPER, ROLES.AUTHORITY, ROLES.ADMIN],
  FIELD: [ROLES.HELPER, ROLES.AUTHORITY, ROLES.ADMIN],
  COMMAND: [ROLES.AUTHORITY, ROLES.ADMIN],
};

export const ROUTE_ACCESS = {
  [ROUTES.VICTIM_DASHBOARD]: [ROLES.VICTIM],
  [ROUTES.SOS]: [ROLES.VICTIM],
  [ROUTES.HELPER_DASHBOARD]: [ROLES.HELPER],
  [ROUTES.ADMIN_DASHBOARD]: ROLE_GROUPS.COMMAND,
  [ROUTES.MAPS]: ROLE_GROUPS.EVERYONE,
  [ROUTES.CHAT]: ROLE_GROUPS.EVERYONE,
  [ROUTES.SHELTERS]: ROLE_GROUPS.EVERYONE,
  [ROUTES.MISSING_PERSONS]: [ROLES.VICTIM, ROLES.HELPER, ROLES.AUTHORITY, ROLES.ADMIN],
  [ROUTES.RESOURCES]: ROLE_GROUPS.FIELD,
  [ROUTES.ALERTS]: ROLE_GROUPS.COMMAND,
  [ROUTES.ANALYTICS]: ROLE_GROUPS.COMMAND,
  [ROUTES.AI]: ROLE_GROUPS.COMMAND,
  [ROUTES.DRONE]: ROLE_GROUPS.COMMAND,
  [ROUTES.UPLOADS]: ROLE_GROUPS.FIELD,
  [ROUTES.REPORTS]: ROLE_GROUPS.COMMAND,
};

export function normalizeRole(role) {
  return String(role || '').trim().toLowerCase();
}

export function canAccessRoute(role, route) {
  const allowedRoles = ROUTE_ACCESS[route];
  return !allowedRoles || allowedRoles.includes(normalizeRole(role));
}

